GITHUB_ORGANIZATION_NAME = 'ucll-programming'
GITHUB_FRONTEND_REPOSITORY_NAME = 'frontend'
IDENTIFIER_FILE = '.identifier'
IDENTIFIER_FILE_CONTENTS = 'UCLL Programming Exercise Repository'
COURSE_MATERIAL_DOCUMENTATION_URL = "https://ucll-programming.github.io/course-material"


ERROR_CODE_MULTIPLE_ASSETS_IN_RELEASE = -1
ERROR_CODE_MISSING_IDENTIFIER_FILE = -2
ERROR_CODE_WRONG_IDENTIFIER_CONTENTS = -3
