GITHUB_ORGANIZATION_NAME = 'ucll-programming'
GITHUB_FRONTEND_REPOSITORY_NAME = 'frontend'
IDENTIFIER_FILE = '.identifier'
IDENTIFIER_FILE_CONTENTS = 'UCLL Programming Exercise Repository'
COURSE_MATERIAL_DOCUMENTATION_URL = 'https://ucll-programming.github.io/course-material'
SETTINGS_FILE_ENVIRONMENT_VARIABLE = 'PROGTOOL_SETTINGS_PATH'

ERROR_CODE_MULTIPLE_ASSETS_IN_RELEASE = -1
ERROR_CODE_MISSING_IDENTIFIER_FILE = -2
ERROR_CODE_WRONG_IDENTIFIER_CONTENTS = -3
ERROR_CODE_GITHUB_ORGANIZATION_NOT_FOUND = -4
