from .settings import settings
from .check import check
from .index import index
from .html import html
from .server import server
from .tree import tree
from .theme import theme
from .cache import cache
from .setup import setup
from .topics import topics
from .version import version
from .relocate import relocate
from .update import update
from .student import student
